export function throw_error() {
	throw  RangeError("Throw exception test")
}
